### ISSUE TITLE
Add support for Filametrix + toolhead and entry sensors

### ISSUE THREAD

**Issue by BenBergman** [rongith/Stealthburner_LGX_Mount#2]
This is probably a tall ask since the extruder body isn't a printed part, but it is what I've got and I want to use it with Filametrix.

I'll try modelling this when I have time, but thought I'd start the issue at least in case I don't get to it before someone else does.

**Comment by rongith** [comment]
You would need to provide some CAD files from a Filametrix. Then I may see how difficult your request is.
